
.. annotated-image:: 80 220 images/shapes.png

   .. annotation:: 22 16 34 36

      **Circle**
         This circle is red. 

   .. annotation:: 10 69 59 75

      **Triangle**
         This is a yellow triangle.

   .. annotation:: 19 158 40 45

      **Square**
         And this is a square.
   
